### ISSUE TITLE
how to catch email sending errors?

### ISSUE THREAD

**Issue by breaklee** [andris9/Nodemailer#414]
i' m using node-mailer for registration mail notification.

but there are some issuses sending mail for invalid email type or wrong email adresses.

how can i catch this state?

**Comment by andris9** [comment]
When sending emails, the callback gets 2 arguments and the first one is an Error object if sending failed.

**Comment by breaklee** [comment]
@andris9 , first one is invalid email address 1@1.com and send result
and second one is valid email address breakdance@lycos.co.kr and  result
both are the same result. so i can not filter sending failure mail address

========================================================================
  null { accepted: [ '1@1.com' ],
  rejected: [],
  response: '250 2.0.0 OK 1428585848 je11sm14359925pbd.65 - gsmtp',
  envelope: { from: 'no_reply@eazler.com', to: [ '1@1.com' ] },
  messageId: '1428585845929-3c6db19f-2f9a58c9-d033dea3@eazler.com' }
========================================================================
  null { accepted: [ 'breakdance@lycos.co.kr' ],
  rejected: [],
  response: '250 2.0.0 OK 1428585888 a2sm690264pdg.70 - gsmtp',
  envelope:
   { from: 'no_reply@eazler.com',
     to: [ 'breakdance@lycos.co.kr' ] },
  messageId: '1428585887124-d99e4fdf-711e5779-6b0b1daf@eazler.com' }

**Comment by andris9** [comment]
Everything is correct in this case. There is no errors because the relay does not know yet that the e-mail address is not valid. Thats what the "bounce" messages are for – if the last SMTP server in the sending chain can't deliver the message then the message is bounced back to the original sender. Nodemailer passes the message to the relay and thats all Nodemailer can do, from this point onwards it is not Nodemailers responsibility to handle the message. Thats how SMTP works.

**Comment by breaklee** [comment]
@andris9 good answer thanks! :)

**Comment by akashgaur** [comment]
but there should a way  to do that ?
how can we get bounce back email using nodemailer ?
or how can we get status code if the smtp server failed to deliver the mail ??
