### ISSUE TITLE
Attachments disappears on iPhone's Mail app

### ISSUE THREAD

**Issue by hugovart** [andris9/Nodemailer#439]
I have a strange problem since I upgraded to Nodemailer v1.3.4 from v0.7
After some adjustments everything worked except attachments does not appear at iPhone's Mail app.
When a message is sent with Nodemailer, I can see the paperclip icon, the attachment is delivered as expected, and it is possible to download the attachment but it just disappears immediately after I tap to view the attachment and it does not show up later on.
This is issue is specific for viewing attachments on iPhone's Mail app. I've tested it on iOS 8.3
The attachments has no problem to be viewed on Gmail's web UI or Gmail's iPhone app.

Here is an example attachment delivered with Nodemailer
```
attachments:
   [ { contentType: 'image/jpeg',
       contentDisposition: 'attachment',
       transferEncoding: 'base64',
       generatedFileName: 'zIm6BAA.jpg',
       contentId: '6b2226d9ad96e922cffb63d191042cc3@mailparser',
       checksum: '7ee730a0c9f0001b92b9420734617c4a',
       length: 812733,
       content: <Buffer ff d8 ff db 00 43 00 03 02 02 03 02 02 03 03 03 03 04 03 03 04 05 08 05 05 04 04 05 0a 07 07 06 08 0c 0a 0c 0c 0b 0a 0b 0b 0d 0e 12 10 0d 0e 11 0e 0b 0b ...>,
       filename: 'zIm6BAA.jpg',
       cid: '6b2226d9ad96e922cffb63d191042cc3@mailparser' } ]
```

**Comment by hugovart** [comment]
I narrowed down the issue to here:
https://github.com/andris9/Nodemailer/blob/f1f6f96523edc07b5dc3fd9f872a821d554c402e/src/compiler.js#L36
the problem occurs when `this._createAlternative()` is used. If `this._createMixed()` were to used, then the attachments does not disappear (on iPhone's Mail app).

**Comment by hugovart** [comment]
Here is another finding. When attachments have `cid` attribute (even though when they are not intended to be used for inline/embedded attachments) then it results in using `this._createAlternative()` instead of `this._createMixed()` at `compiler.js`as stated above ([see: compiler.js#278](https://github.com/andris9/Nodemailer/blob/f1f6f96523edc07b5dc3fd9f872a821d554c402e/src/compiler.js#L278)). Which eventually causes attachments to **disappear** at iPhone's mail app.

**Comment by andris9** [comment]
This behavior is intentional. If an attachment has the `cid` value set, then it is considered as an addition to the main content, not something separate and the attachment is moved from the mixed node to the related node.

"Normal" attachment would be located in the multipart/mixed node like this:
```
- root
  - multipart/mixed
    - multipart/alternative
      - text/html
      - text/plain
    - attachment
```

Attachment with `cid` value is located in the related node together with the html content:
```
- root
  - multipart/alternative
    - multipart/related
      - text/html
      - attachment
    - text/plain
```

"Related" attachments are not regular downloadable attachments but are part of the actual content (eg. embedded images). Nodemailer does not know if the attachment with `cid` is actually linked from the content or not (the content might be a stream or URL etc. which is resolved when the client is already sending the message and by that time the structure of the message is already composed. If you do not want to have your non-related attachments in the related node, then remove the `cid` value.

**Comment by hugovart** [comment]
That makes sense. Thanks!

**Comment by davidhouweling** [comment]
What would be the solution to perform [embedded images](http://nodemailer.com/using-embedded-images/) that would work with iOS then?

**Comment by niftylettuce** [comment]
Try this package: https://github.com/crocodilejs/nodemailer-base64-to-s3
