### ISSUE TITLE
Unable to send email due to DMARC Policy.

### ISSUE THREAD

**Issue by XanderDwyl** [andris9/Nodemailer#469]
Hi,

I'm using this nodemailer but it seems that it would not allowed to send email from yahoo to gmail domain. When I check me mailer server, it says 'Unauthenticated email from yahoo.com is not accepted due to domain\'s\n550-5.7.1 DMARC policy'. Any one knows how configure this error? 

Thanks,
Xander

**Comment by andris9** [comment]
What is your configuration? Are you trying to send mail directly to Gmail or through the Yahoo SMTP servers?

**Comment by XanderDwyl** [comment]
Hi @andris9,

I use direct transport.

var transporter = nodemailer.createTransport( );

**Comment by andris9** [comment]
With direct transport your computer (or server) is connecting to Gmail and tries to send mail from an yahoo.com address while Yahoo has stated that only servers that belong to Yahoo are eligible to send mail for yahoo.com addresses. Instead of direct transports use smtpTransport with your yahoo credentials, in this case the mail is proxied through Yahoo servers and the mail is accepted by others servers.
