### ISSUE TITLE
Proposed "official" place to put send options

### ISSUE THREAD

**Issue by devinus** [andris9/Nodemailer#481]
Author of 2 (soon 3) Nodemailer integrations. I need a sanctioned place to put options that the underlying client accepts when using `send`.

E.g.

`transport.sendMail({ to: ..., options: { clientSpecificOption: true } })`

**Comment by andris9** [comment]
Actually I do not have a strong opinion on this. I see that there could be potential conflicts in the long term where different authors try to use the same option keys but for now I don't think there's an issue. I would leave it up to the authors, at least for now. If you do not care about conflicts then use the root of the options object, otherwise try to use some kind of custom subkeys, eg `{to:..., myplugin: {...}}`

**Comment by devinus** [comment]
@andris9 One great thing I love about Nodemailer is that the options and what they *should* mean are all well documented. So I try to keep my transports "in spec" so people know what to expect. It becomes intuitive to have multiple transports. It would be great if that was the case for a place to put these options rather than dumping them at the root. Maybe something like a **transports** key. E.g. `options.transports.mandrill.options`.

**Comment by andris9** [comment]
I agree that this would be a better approach than the current *everything-in-root* but it's not possible to change the already existing stuff without breaking something and thus there would always be inconsistencies between different modules/transports.
