### ISSUE TITLE
Sending via gmail failed

### ISSUE THREAD

**Issue by Ulawun** [andris9/Nodemailer#515]
Hello Mailers,
When I check out the github demo code
(sending a mail via gmail),
I get attached error.
I successfully logged in at google and checked again -> same error.
Any ideas please ?
Thanks.

{ [Error: Invalid login]
  code: 'EAUTH',
  response: '534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1
&plt=AKgnsbvTx\n534-5.7.14 9r1Ek0CXdMUxJ7ZxkXvj1zoJ497Hd6x0DdN9dIQAMoLxjCtxDWIea
bq8F8vX7cPieMmQXc\n534-5.7.14 -Iy52ZHvmujVE3-i8yvxiz3qCk77DlXg6AmXGKnle1jksnA5km
lV1NufScIVpt14Y2B8g4\n534-5.7.14 J-2HLuRAm2PAw5O3I95RJB1Deb1ALAk_ma8SgYZ0u9D2MYu
PauDUG_Yjazb7tOcrzA39Te\n534-5.7.14 5IcpUApVo7DiXt4xlrn5ylX5qk58> Please log in
via your web browser and\n534-5.7.14 then try again.\n534-5.7.14  Learn more at\
n534 5.7.14  https://support.google.com/mail/answer/78754 77sm13524842wml.20 - g
smtp', responseCode: 534 }

**Comment by andris9** [comment]
You may need to ["Allow Less Secure Apps"](https://www.google.com/settings/security/lesssecureapps) in your gmail account (it's all the way at the bottom). You also may need to ["Allow access to your Google account"](https://accounts.google.com/DisplayUnlockCaptcha). See details about using Gmail [here](https://github.com/andris9/Nodemailer#using-gmail).

**Comment by Ulawun** [comment]
Thanks a lot and a great day :-)

**Comment by cccabdalla** [comment]
@andris9 , did all but still facing the same error  as that one of @Ulawun

**Comment by atriumstudios** [comment]
[Allow access to your google account](https://accounts.google.com/DisplayUnlockCaptcha) above helped after hours of messing around with allow less secure apps.

**Comment by avillarubia** [comment]
@andris9 thank you it works

**Comment by temitopealabi** [comment]
@atriumstudios your suggestions work  for me .thanks

**Comment by JerfsonAugusto** [comment]
@andris9  thank you it works

**Comment by Oscarcontreras0** [comment]
Have you ever experienced being scammed in the past, whether through investment or impersonation? It’s crucial to remember that feeling ashamed of mistakes is unnecessary, as these experiences contribute to our growth and wisdom. Fortunately, there are now solutions available for recovering lost funds, and my personal experience with Cyber Constable Intelligence is a testament to their effectiveness. My ordeal began with what I believed to be a promising investment opportunity. I had invested £209,000 into a website that seemed legitimate and was promising significant returns. Over just two weeks, I saw my investment grow by over £190,000 in profits. The platform’s claims and the rapid increase in my account balance made me feel confident and optimistic about the future. However, when I attempted to withdraw my profits, things took a sudden turn for the worse. I received a message instructing me to contact support to process the withdrawal. Naively, I followed the instructions, only to discover that my supposed profits were fabricated. The realization that I had been scammed and that my funds were effectively trapped on a fraudulent website was deeply unsettling. The anxiety and frustration were compounded by the fact that my initial investment was now at risk, and all my plans based on those profits came to an abrupt halt. Desperate to reclaim my money, I explored every possible avenue I could think of. I tried contacting the platform’s support, sought advice from online forums, and even reached out to local authorities. Despite my best efforts, I found that none of these actions led to a resolution. Each attempt seemed to bring more frustration and despair, and the hope of recovering my funds seemed to diminish.  I contacted Cyber Constable Intelligence, explaining the details of my predicament and providing all necessary information about the fraudulent website and my investments. The team at Cyber Constable Intelligence responded promptly and with great professionalism. Their approach was thorough, involving detailed investigations and advanced techniques to trace and recover my funds. The process wasn’t instant, but Cyber Constable Intelligence’s diligence and expertise eventually paid off. After working with their team, I was able to recover my original investment of £209,000.  Now that my original funds are safely recovered, I can shift my focus to more reliable and resourceful investment opportunities, ones that do not involve the risks and uncertainties associated with digital scams. The experience has taught me valuable lessons about due diligence and the importance of verifying the legitimacy of any investment opportunity before committing funds. For anyone facing a similar situation, where you’ve been scammed or have lost money to a fraudulent scheme, I strongly recommend reaching out to Cyber Constable Intelligence. Their expertise and commitment to helping individuals in distress can make a substantial difference. They offer a viable solution to reclaiming lost funds and navigating the complexities of financial fraud recovery. while being scammed can be an incredibly frustrating and disheartening experience, it is essential to know that there are resources available to help you recover your losses. Cyber Constable Intelligence demonstrated their capability and dedication in assisting me, and I am grateful for their support. If you find yourself in need of assistance with recovering lost funds, don’t hesitate to contact Cyber Constable Intelligence—they could be the key to regaining what you’ve lost and moving forward with confidence.
Information of Cyber Constable Intelligence

WhatsApp info: + 1 2 5 2 3 7 8 7 6 1 1

Website info: https://cyberconstableintelligence…... com)

Email info: (support (@) cyberconstableintelligence ).  com)

**Comment by Alexandernna** [comment]
Hi everyone. I’m  Alexander Anna from Mesa, Arizona. I was one of the victims of a crypto investment scam that saw me lose $302,000 worth of crypto. The crypto market is very volatile and a lot of individuals have lost some of their crypto coins and crypto assets to these online scams. My wallet address was compromised and I don’t know how they got a hold of my recovery phrase, but I was wiped out by these scam attacks. I lost all my crypto coins (ethereum, Btc & USDT) and this left me devastated and depressed. I could have been homeless if it was not for the intervention of CYBER SPACE HACKPRO, a well-known and highly trusted crypto company whom I contacted through a colleague of mine, I filed a complaint to CYBER SPACE HACKPRO and provided them with all the information including screenshots of the transactions. CYBER SPACE HACKPRO was able to recover my crypto assets in less than 48 hours. I was totally in awe of how quickly and efficiently CYBER SPACE HACKPRO was able to access my stolen crypto and recover my crypto wallet and assets. I’m highly impressed and I recommend their services to everyone. Truly information is very valuable and without the help of CYBER SPACE HACKPRO, I could have been homeless and left in a pitiful state. I’m very thankful for their help and I’m glad there is a safe way to fully recover crypto assets since the authorities cannot do anything to help get back lost funds. CYBER SPACE HACKPRO was able to help me trace these conmen with their sophisticated CYBER SPACE HACKPRO system. You can easily contact CYBER SPACE HACKPRO with the following information.


https://cyberspacehackpro0.wixsite.com/cyberspacehackpro 

WhatsApp:  +1 -559- 508-2403

Email: Cyberspacehackpro (@) rescueteam. com
![Uploading 7cb40539-8b96-4950-9ce5-c039c12091ee (1).jpeg…]()
