### ISSUE TITLE
Use bluebird promises if bluebird is present

### ISSUE THREAD

**Issue by BridgeAR** [andris9/Nodemailer#516]
I like that you implemented Promises for sendMail but right now the implementation has two downsides:

1. It does not work on older nodejs versions that have no native Promises
2. If someone is interested in long stack traces or additional Promise features they won't be present

So I suggest to check if bluebird is already present in the node modules (this is very likely for almost any bigger project at least as a peer dependency) and use those Promises instead of the native ones if present.

This has the benefit that older Nodejs versions get support for promises too, the implementation is faster, has long stack traces (if activated) and more features. If you like the idea I'm willing to provide a PR.

**Comment by andris9** [comment]
I don't want to add 3rd party APIs if there's already a native one, especially when bluebird is not the only non-native Promise implementation. Besides, there already is a simple way to add bluebird support to Nodemailer, see [Nodemailer example](http://bluebirdjs.com/docs/working-with-callbacks.html#more-common-examples) from the bluebird homepage. 

Promises are available since Node.js 0.12 and I'm not trying to keep up feature parity with Node.js 0.10 anymore, even the unit tests for Nodmailer require at least Node.js 0.12.
